---
title: Anish Joshi
timezone: America/New_York
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:path/"
  publications:
    title: Publications
    output: true
    permalink: "/:collection/:path/"
  talks:
    title: Talks
    output: true
    permalink: "/:collection/:path/"
  teaching:
    title: Teaching
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: teaching
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: projects
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: portfolio
  values:
    layout: single
    author_profile: true
    share: true
    comment: true
- scope:
    path: ''
    type: talks
  values:
    layout: talk
    author_profile: true
    share: true
locale: en-US
title_separator: "-"
name: Anish Joshi
description: I am a Masters student at the Dept. of Computer Science and Engineering,
  The State University of New York at Buffalo.
url: https://anishana.github.io
baseurl: ''
repository: anishana.github.io
teaser: 
breadcrumbs: false
words_per_minute: 160
future: true
read_more: enabled
talkmap_link: false
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: master
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: o8lyh5anEQ1z8ihJmo9DpjnkB21PmVGL9FPwDgTons8
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: google-universal
  google:
    tracking_id: 
author:
  name: Anish Joshi
  avatar: Profile_pic_1.jpg
  bio: I hold a Masters degree from the Dept. of Computer Science and Engineering,
    The State University of New York at Buffalo.
  location: Seattl, WA
  email: anishana@buffalo.edu
  github: anishana
  linkedin: 
  stackoverflow: 
  twitter: AnishJoshi06
include:
- ".htaccess"
- _pages
- files
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- assets/js/_main.js
- assets/js/plugins
- assets/js/vendor
- config
- gulpfile.js
- log
- node_modules
- package.json
- tmp
- vendor
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
